# Generated by Django 3.0 on 2020-04-25 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200425_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 16, 48, 43, 406923), verbose_name='date published'),
        ),
    ]
