# Generated by Django 3.0 on 2020-04-25 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200425_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 25, 17, 9, 43, 661387), verbose_name='date published'),
        ),
    ]
